# Generated by Django 4.2.2 on 2023-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('spieces', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], default='cat', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('png', 'png'), ('jpg', 'jpg'), ('gif', 'gif')], default='cat', max_length=5)),
            ],
        ),
    ]
